alter table EMPLOYMENT_CITIZEN add constraint FK_EMPLOYMENT_CITIZEN_ON_PROFESSION foreign key (PROFESSION_ID) references EMPLOYMENT_PROFESSION(ID);
create index IDX_EMPLOYMENT_CITIZEN_ON_PROFESSION on EMPLOYMENT_CITIZEN (PROFESSION_ID);
